<?php
/*
 * Localization file for ident_switch plugin
 */
$labels = array();

// Plugin ident_switch
$labels['form.common.caption'] = 'Plugin ident_switch';

// Enabled
$labels['form.common.enabled'] = 'Enabled';

// Label
$labels['form.common.label'] = 'Label';

// Value in \'Label\' field is too long (32 chars max).
$labels['err.label.long'] = 'Value in \'Label\' field is too long (32 chars max).';


// IMAP
$labels['form.imap.caption'] = 'IMAP';

// Server host name
$labels['form.imap.host'] = 'Server host name';

// Secure connection (TLS)
$labels['form.imap.tls'] = 'Secure connection (TLS)';

// Port
$labels['form.imap.port'] = 'Port';

// Folder hierarchy delimiter
$labels['form.imap.delimiter'] = 'Folder hierarchy delimiter';

// Username
$labels['form.imap.username'] = 'Username';

// Password
$labels['form.imap.password'] = 'Password';

// Value in \'Username\' field is too long (64 chars max).
$labels['err.user.long'] = 'Value in \'Username\' field is too long (64 chars max).';


// SMTP
$labels['form.smtp.caption'] = 'SMTP';

// Server host name
$labels['form.smtp.host'] = 'Server host name';

// Secure connection (TLS)
$labels['form.smtp.tls'] = 'Secure connection (TLS)';

// Port
$labels['form.smtp.port'] = 'Port';

// Authorization
$labels['form.smtp.auth'] = 'Authorization';

// As IMAP
$labels['form.smtp.auth.imap'] = 'As IMAP';

// None
$labels['form.smtp.auth.none'] = 'None';


// Errors

// Value in \'Server host name\' field is too long (64 chars max).
$labels['err.host.long'] = 'Value in \'Server host name\' field is too long (64 chars max).';

// Value in \'Port\' field must be a number.
$labels['err.port.num'] = 'Value in \'Port\' field must be a number.';

// Value in \'Port\' field must be between 1 and 65535.
$labels['err.port.range'] = 'Value in \'Port\' field must be between 1 and 65535.';
